using ClassifiedAds.Application.DTOs.Common;
using FluentValidation;

namespace ClassifiedAds.Application.Validators.Common;

public class AdImageDtoValidator : AbstractValidator<AdImageDto>
{
    public AdImageDtoValidator()
    {
        // ImageId is optional - auto-generated by MongoDB on create
        RuleFor(x => x.ImageId)
            .MaximumLength(24)
            .WithMessage("Image ID must not exceed 24 characters")
            .When(x => !string.IsNullOrEmpty(x.ImageId));

        RuleFor(x => x.ImageUrl)
            .NotEmpty()
            .WithMessage("Image URL is required")
            .MaximumLength(500)
            .WithMessage("Image URL must not exceed 500 characters");

        RuleFor(x => x.Order)
            .InclusiveBetween((byte)1, (byte)5)
            .WithMessage("Image order must be between 1 and 5");
    }
}
